server {

    listen 80;

    server_name _;

    root /usr/share/nginx/html;

    index index.html;

    #
    # Compressão Gzip
    #
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 1024;

    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/xml
        application/rss+xml
        application/vnd.ms-fontobject
        application/x-font-ttf
        font/opentype
        image/svg+xml;

    #
    # Site
    #
    location / {
        try_files $uri $uri/ /index.html;
    }

    #
    # Cache de arquivos estáticos
    #
    location ~* \.(css|js|png|jpg|jpeg|gif|svg|ico|woff|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

}